### 
    opencv-python
    scikit-imgage
    matplotlib

## difference btw range() and arange()
    range will return list whereas arange will return array
    

In [2]:
import numpy as np

In [3]:
np.random.randint(1,10)

6

In [4]:
np.random.randint(1,10,3)

array([4, 7, 5])

In [13]:
np.random.seed(188)
np.random.randint(1,23,[3,4])

array([[19,  2,  3,  1],
       [17, 12,  4,  5],
       [21,  8, 14, 21]])

In [22]:
np.random.rand(2,4)   # ---> generate floating point btw 0.1 to 1.0

array([[0.92806144, 0.15622622, 0.66625766, 0.48554817],
       [0.71434743, 0.08016041, 0.21903236, 0.04558478]])

In [24]:
np.random.randn(2)   #negative

array([-1.50004493,  1.30111221])

In [27]:
np.loadtxt('data.txt',dtype='str')

array([['hi', 'my', 'name', 'is', 'rahul'],
       ['this', 'is', 'my', 'first', 'class']], dtype='<U5')

In [28]:
a = np.random.randint(1,300,[3,5])
a

array([[ 56, 210, 185,   2,  38],
       [228, 220,  93, 179, 265],
       [ 65, 136, 280, 164, 247]])

In [32]:
np.savetxt('data2.txt',a,delimiter='|',fmt = '%d')

In [34]:
a.sum(axis = 1) # rows


array([491, 985, 892])

In [35]:
a.mean()

157.86666666666667

In [38]:
a.argmax(axis = 1)

array([1, 4, 2], dtype=int64)

In [37]:
a

array([[ 56, 210, 185,   2,  38],
       [228, 220,  93, 179, 265],
       [ 65, 136, 280, 164, 247]])

In [39]:
a.max()

280

In [40]:
a.flatten()

array([ 56, 210, 185,   2,  38, 228, 220,  93, 179, 265,  65, 136, 280,
       164, 247])